<?php

return array(
    'linux' => array(
        'title' => 'Линукс',
        'href' => 'doc.php?path=linux',
        'style' =>'border: 4px dotted #000000;',
        'img' =>'logo/linux.png',
        'cls' =>'div-logo',
        'activable' => true,
        'items' => array(),
    ),
    'php' => array(
        'title' => 'PHP: Hypertext Preprocessor',
        'href' => 'php.php',
        'style' =>'border: 4px dotted #8ba9d9;',
        'img' =>'logo/php.png',
        'cls' =>'div-logo',
        'activable' => true,
        'items' => array(
            'php' => array(
                'title' => 'PHP: Hypertext Preprocessor',
                'href' => 'doc.php?path=php',
                'style' =>'border: 4px dotted #8ba9d9;',
                'img' =>'logo/php.png',
                'cls' =>'div-logo',
                'activable' => true,
                'items' => array(),
            ),
        ),
    ),
    'mysql' => array(
        'title' => 'MySQL',
        'href' => 'doc.php?path=mysql',
        'style' =>'border: 4px dotted #004b62;',
        'img' =>'logo/mysql.png',
        'cls' =>'div-logo',
        'activable' => true,
        'items' => array(),
    ),
    'proectirovanie' => array(
        'title' => 'Проектирование: Шаблоны и алгоритмы',
        'href' => 'architecture.php',
        'style' =>'border: 4px dotted #004b62;',
        'img' =>'logo/design.png',
        'cls' =>'div-logo',
        'activable' => true,
        'items' => array(
            'patterns' => array(
                'title' => 'ООП Шаблоны проектирования',
                'href' => 'doc.php?path=patterns',
                'style' =>'border: 4px dotted #004b62;',
                'img' =>'logo/mvc.png',
                'cls' =>'div-logo',
                'activable' => true,
                'items' => array(),
            ),
        ),
    ),
    'htmlcss' => array(
        'title' => 'HTML5 и CSS3',
        'href' => 'doc.php?path=htmlcss',
        'style' =>'border: 4px dotted #000000;',
        'img' =>'logo/htmlcss.png',
        'cls' =>'div-logo',
        'activable' => false,
        'items' => array(),
    ),
    'javascript' => array(
        'title' => 'JavaScript',
        'href' => 'js.php',
        'style' =>'border: 4px dotted #3dade9;',
        'img' =>'logo/javascript.png',
        'cls' =>'div-logo',
        'activable' => true,
        'items' => array(
            'js' => array(
                'title' => 'JavaScript',
                'href' => 'doc.php?path=js',
                'style' =>'border: 4px dotted #3dade9;',
                'img' =>'logo/javascript.png',
                'cls' =>'div-logo',
                'activable' => true,
                'items' => array(),
            ),
            'jsevents' => array(
                'title' => 'JavaScript Events',
                'href' => 'doc.php?path=js-events',
                'style' =>'border: 4px dotted #3dade9;',
                'img' =>'logo/javascript.png',
                'cls' =>'div-logo',
                'activable' => true,
                'items' => array(),
            ),
            'jsdocument' => array(
                'title' => 'Документ и объекты страницы',
                'href' => 'doc.php?path=jsdocument',
                'style' =>'border: 4px dotted #3dade9;',
                'img' =>'logo/javascript.png',
                'cls' =>'div-logo',
                'activable' => true,
                'items' => array(),
            ),
            'jsoop' => array(
                'title' => 'ООП а javascript',
                'href' => 'doc.php?path=jsoop',
                'style' =>'border: 4px dotted #3dade9;',
                'img' =>'logo/javascript.png',
                'cls' =>'div-logo',
                'activable' => true,
                'items' => array(),
            ),
            'jses6' => array(
                'title' => 'ECMA script 2015 (ECMA-262, ES6)',
                'href' => 'doc.php?path=jses6',
                'style' =>'border: 4px dotted #3dade9;',
                'img' =>'logo/javascript.png',
                'cls' =>'div-logo',
                'activable' => true,
                'items' => array(),
            ),
            'jquery' => array(
                'title' => 'jQuery',
                'href' => '#',
                'style' =>'border: 4px dotted #0868ab;',
                'img' =>'logo/jqurery.png',
                'cls' =>'div-logo',
                'activable' => false,
                'items' => array(),
            ),
            'd3' => array(
                'title' => 'd3 - Data-Driven Documents',
                'href' => 'doc.php?path=d3',
                'style' =>'border: 4px dotted #c1574f;',
                'img' =>'logo/d3.png',
                'cls' =>'div-logo',
                'activable' => false,
                'items' => array(),
            ),
            'extjs' => array(
                'title' => 'extjs',
                'href' => 'doc.php?path=extjs',
                'style' =>'border: 4px dotted #009900;',
                'img' =>'logo/extjs.png',
                'cls' =>'div-logo',
                'activable' => false,
                'items' => array(),
            ),
            'angular' => array(
                'title' => 'angular',
                'href' => '#',
                'style' =>'border: 4px dotted #e23237;',
                'img' =>'logo/angular.png',
                'cls' =>'div-logo',
                'activable' => false,
                'items' => array(),
            ),
            'backbone' => array(
                'title' => 'backbone',
                'href' => '#',
                'style' =>'border: 4px dotted #0072b9;',
                'img' =>'logo/backbone.png',
                'cls' =>'div-logo',
                'activable' => false,
                'items' => array(),
            ),
            'knockout' => array(
                'title' => 'knockout',
                'href' => '#',
                'style' =>'border: 4px dotted #000000;',
                'img' =>'logo/knockout.png',
                'cls' =>'div-logo',
                'activable' => false,
                'items' => array(),
            ),
            'ember' => array(
                'title' => 'ember',
                'href' => '#',
                'style' =>'border: 4px dotted #ff492b;',
                'img' =>'logo/ember.png',
                'cls' =>'div-logo',
                'activable' => false,
                'items' => array(),
            ),
            'react' => array(
                'title' => 'react',
                'href' => 'doc.php?path=react',
                'style' =>'border: 4px dotted #00dbfb;',
                'img' =>'logo/react.png',
                'cls' =>'div-logo',
                'activable' => false,
                'items' => array(),
            ),
            'dojo' => array(
                'title' => 'dojo',
                'href' => '#',
                'style' =>'border: 4px dotted #000000;',
                'img' =>'logo/dojo.png',
                'cls' =>'div-logo',
                'activable' => false,
                'items' => array(),
            ),
            'electron' => array(
                'title' => 'electron',
                'href' => 'doc.php?path=electron',
                'style' =>'border: 4px dotted #67595d;',
                'img' =>'logo/electron.png',
                'cls' =>'div-logo',
                'activable' => false,
                'items' => array(),
            ),
        ),
    ),
    'zf2' => array(
        'title' => 'Zend Framework 2',
        'href' => '#',
        'style' =>'border: 4px dotted #0fb700;',
        'img' =>'logo/zf.png',
        'cls' =>'div-logo',
        'activable' => false,
        'items' => array(),
    ),
    'bootstrap' => array(
        'title' => 'Twitter Bootstrap',
        'href' => 'doc.php?path=bootstrap',
        'style' =>'border: 4px dotted #00a7d4;',
        'img' =>'logo/bootstrap.png',
        'cls' =>'div-logo',
        'activable' => false,
        'items' => array(),
    ),
    'doctrine' => array(
        'title' => 'Doctrine ORM',
        'href' => '#',
        'style' =>'border: 4px dotted #ff852f;',
        'img' =>'logo/doctrine.png',
        'cls' =>'div-logo',
        'activable' => false,
        'items' => array(),
    ),
    'git' => array(
        'title' => 'GIT SCM',
        'href' => 'doc.php?path=git',
        'style' =>'border: 4px dotted #ff3929;',
        'img' =>'logo/git.png',
        'cls' =>'div-logo',
        'activable' => true,
        'items' => array(),
    ),
    'hg' => array(
        'title' => 'Mercurial SCM',
        'href' => 'doc.php?path=hg',
        'style' =>'border: 4px dotted #999999;',
        'img' =>'logo/hg.png',
        'cls' =>'div-logo',
        'activable' => true,
        'items' => array(),
    ),
    'mongo' => array(
        'title' => 'MongoDB: NOSQL СУБД',
        'href' => '#',
        'style' =>'border: 4px dotted #009900;',
        'img' =>'logo/mongo.png',
        'cls' =>'div-logo',
        'activable' => false,
        'items' => array(),
    ),
    'redis' => array(
        'title' => 'Redis: REmote DIctionary Server',
        'href' => '#',
        'style' =>'border: 4px dotted #bb1207;',
        'img' =>'logo/redis.png',
        'cls' =>'div-logo',
        'activable' => false,
        'items' => array(),
    ),
    'smarty' => array(
        'title' => 'Smarty: PHP Template Engine',
        'href' => '#',
        'style' =>'border: 4px dotted #ffc12b; background: #ffc12b;',
        'img' =>'logo/smarty.png',
        'cls' =>'div-logo',
        'activable' => false,
        'items' => array(),
    ),
    'sphinx' => array(
        'title' => 'Sphinx: Open Source Search Engine',
        'href' => '#',
        'style' =>'border: 4px dotted #2bb3dd;',
        'img' =>'logo/sphinx.png',
        'cls' =>'div-logo',
        'activable' => false,
        'items' => array(),
    ),
    'yii' => array(
        'title' => 'YII: PHP Framework',
        'href' => '#',
        'style' =>'border: 4px dotted #2bb3dd;',
        'img' =>'logo/yii.png',
        'cls' =>'div-logo',
        'activable' => false,
        'items' => array(),
    ),
    'arduino' => array(
        'title' => 'Ардуино скетчи',
        'href' => 'doc.php?path=arduino',
        'style' =>'border: 4px dotted #2bb3dd;',
        'img' =>'logo/arduino.png',
        'cls' =>'div-logo',
        'activable' => true,
        'items' => array(),
    ),
    'c' => array(
        'title' => 'Си++',
        'href' => 'doc.php?path=cpp',
        'style' =>'border: 4px dotted #004381;',
        'img' =>'logo/cpp.png',
        'cls' =>'div-logo',
        'activable' => false,
        'items' => array(),
    ),
    'books' => array(
        'title' => 'Полезные книги',
        'href' => 'books.php',
        'style' =>'border: 4px dotted #561311;',
        'img' =>'logo/books.png',
        'cls' =>'div-logo',
        'activable' => true,
        'items' => array(
            'algorithms' => array(
                'title' => 'Алгоритмы. Построение и анализ Авторы: Томас Кормен, Чарльз Лейзерсон, Рональд',
                'href' => 'doc.php?path=algorithms',
                'style' =>'border: 4px dotted #000000;',
                'img' =>'logo/books/algo.png',
                'cls' =>'div-logo',
                'activable' => false,
                'items' => array(),
            ),
            'idealprog' => array(
                'title' => 'Идеальный программист. Как стать профессионалом разработки ПО',
                'href' => 'doc.php?path=idealprog',
                'style' =>'border: 4px dotted #000000;',
                'img' =>'logo/books/idealprog.png',
                'cls' =>'div-logo',
                'activable' => false,
                'items' => array(),
            ),
            'hl' => array(
                'title' => 'Разработка высоконагруженных систем',
                'href' => 'doc.php?path=hl',
                'style' =>'border: 4px dotted #000000;',
                'img' =>'logo/books/hl.png',
                'cls' =>'div-logo',
                'activable' => false,
                'items' => array(),
            ),
            'pragmatic' => array(
                'title' => 'Программист-прагматик Э. Хант, Д. Томас',
                'href' => 'doc.php?path=pragmatic',
                'style' =>'border: 4px dotted #000000;',
                'img' =>'logo/books/pragmatik.png',
                'cls' =>'div-logo',
                'activable' => false,
                'items' => array(),
            ),
            'architecture' => array(
                'title' => 'Архитектура корпоративных приложений (М. Фаулер)',
                'href' => 'doc.php?path=architecture',
                'style' =>'border: 4px dotted #000000;',
                'img' =>'logo/books/architect.png',
                'cls' =>'div-logo',
                'activable' => false,
                'items' => array(),
            ),
            'cleancode' => array(
                'title' => 'Чистый код Р. Мартин',
                'href' => 'doc.php?path=cleancode',
                'style' =>'border: 4px dotted #000000;',
                'img' =>'logo/books/clean.png',
                'cls' =>'div-logo',
                'activable' => false,
                'items' => array(),
            ),
            'extreme' => array(
                'title' => 'Экстремальное программирование: разработка через тестирование. Кент Бек. (Test-driven Development by Example).',
                'href' => 'doc.php?path=extreme',
                'style' =>'border: 4px dotted #000000;',
                'img' =>'logo/books/exstreme.png',
                'cls' =>'div-logo',
                'activable' => false,
                'items' => array(),
            ),
            'perfect' => array(
                'title' => 'Совершенный код С. Макконнелл',
                'href' => 'doc.php?path=perfect',
                'style' =>'border: 4px dotted #000000;',
                'img' =>'logo/books/ideal.png',
                'cls' =>'div-logo',
                'activable' => false,
                'items' => array(),
            ),
            'artofprogramming' => array(
                'title' => 'Искусство программирования Д. Кнут',
                'href' => 'doc.php?path=artofprogramming',
                'style' =>'border: 4px dotted #000000;',
                'img' =>'logo/books/knut.png',
                'cls' =>'div-logo',
                'activable' => false,
                'items' => array(),
            ),
            'nosql' => array(
                'title' => 'NoSQL Distilled Мартин Фаулер',
                'href' => 'doc.php?path=nosql',
                'style' =>'border: 4px dotted #000000;',
                'img' =>'logo/books/nosql.png',
                'cls' =>'div-logo',
                'activable' => true,
                'items' => array(),
            ),
            'designpatterns' => array(
                'title' => 'Паттерны проектирования Э. Гамма, Р. Хелм, Р. Джонсон, Д. Влиссидес',
                'href' => 'doc.php?path=designpatterns',
                'style' =>'border: 4px dotted #000000;',
                'img' =>'logo/books/oop.png',
                'cls' =>'div-logo',
                'activable' => false,
                'items' => array(),
            ),
            'refactoring' => array(
                'title' => 'Рефакторинг. Улучшение существующего кода (Мартин Фаулер)',
                'href' => 'doc.php?path=refactoring',
                'style' =>'border: 4px dotted #000000;',
                'img' =>'logo/books/refact.png',
                'cls' =>'div-logo',
                'activable' => false,
                'items' => array(),
            ),
            'structure' => array(
                'title' => 'Структура и Интерпретация Компьютерных Программ Авторы: Харольд Абельсон, Джеральд Джей Сассман',
                'href' => 'doc.php?path=structure',
                'style' =>'border: 4px dotted #000000;',
                'img' =>'logo/books/structure.png',
                'cls' =>'div-logo',
                'activable' => false,
                'items' => array(),
            ),
            'ddd' => array(
                'title' => 'Предметно-ориентированное проектирование (DDD). Структуризация сложных программных систем. Ерик Эванс. (Tackling Complexity in the Heart of Software)',
                'href' => 'doc.php?path=ddd',
                'style' =>'border: 4px dotted #000000;',
                'img' =>'logo/books/ddd.png',
                'cls' =>'div-logo',
                'activable' => false,
                'items' => array(),
            ),
        ),
    ),
    'java' => array(
        'title' => 'Java',
        'href' => 'java.php',
        'style' =>'border: 4px dotted #3dade9;',
        'img' =>'logo/java.png',
        'cls' =>'div-logo',
        'activable' => true,
        'items' => array(
            'java' => array(
                'title' => 'Программирование на языке Java',
                'href' => 'doc.php?path=java',
                'style' =>'border: 4px dotted #3dade9;',
                'img' =>'logo/java.png',
                'cls' =>'div-logo',
                'activable' => true,
                'items' => array(),
            ),
            'android' => array(
                'title' => 'Android',
                'href' => 'doc.php?path=android',
                'style' =>'border: 4px dotted #a4c639;',
                'img' =>'logo/android.png',
                'cls' =>'div-logo',
                'activable' => true,
                'items' => array(),
            ),
            'libgdx' => array(
                'title' => 'libgdx',
                'href' => 'doc.php?path=libgdx',
                'style' =>'border: 4px dotted #f50000;',
                'img' =>'logo/libgdx.png',
                'cls' =>'div-logo',
                'activable' => true,
                'items' => array(),
            ),
        ),
    ),
    'testing' => array(
        'title' => 'Тестирование',
        'href' => 'testing.php',
        'style' =>'border: 4px dotted #000000;',
        'img' =>'logo/testing.png',
        'cls' =>'div-logo',
        'activable' => true,
        'items' => array(
            'jasmine' => array(
                'title' => 'Jasmine: Behavior-Driven JavaScript',
                'href' => 'doc.php?path=jasmine',
                'style' =>'border: 4px dotted #c1574f;',
                'img' =>'logo/jasmine.png',
                'cls' =>'div-logo',
                'activable' => false,
                'items' => array(),
            ),
            'phpunit' => array(
                'title' => 'PHP: Hypertext Preprocessor',
                'href' => 'doc.php?path=phpunit',
                'style' =>'border: 4px dotted #8ba9d9;',
                'img' =>'logo/phpunit.png',
                'cls' =>'div-logo',
                'activable' => true,
                'items' => array(),
            ),
        ),
    ),
    'webservers' => array(
        'title' => 'webservers',
        'href' => 'webservers.php',
        'style' =>'border: 4px dotted #3dade9;',
        'img' =>'logo/webserver.png',
        'cls' =>'div-logo',
        'activable' => true,
        'items' => array(
            'apache' => array(
                'title' => 'apache',
                'href' => 'doc.php?path=apache',
                'style' =>'border: 4px dotted #cb1d58;',
                'img' =>'logo/apache.png',
                'cls' =>'div-logo',
                'activable' => true,
                'items' => array(),
            ),
            'nginx' => array(
                'title' => 'nginx',
                'href' => 'doc.php?path=nginx',
                'style' =>'border: 4px dotted #009639;',
                'img' =>'logo/nginx.png',
                'cls' =>'div-logo',
                'activable' => true,
                'items' => array(),
            ),
            'fpm' => array(
                'title' => 'fpm',
                'href' => 'doc.php?path=fpm',
                'style' =>'border: 4px dotted #6881b7;',
                'img' =>'logo/fpm.png',
                'cls' =>'div-logo',
                'activable' => true,
                'items' => array(),
            ),
        ),
    ),
    'security' => array(
        'title' => 'Безопасность и криптография',
        'href' => 'doc.php?path=security',
        'style' =>'border: 4px dotted #000000;',
        'img' =>'logo/security.png',
        'cls' =>'div-logo',
        'activable' => true,
        'items' => array(),
    ),
    'nodejs' => array(
        'title' => 'Node.js',
        'href' => 'doc.php?path=nodejs',
        'style' =>'border: 4px dotted #78bf33;',
        'img' =>'logo/nodejs.png',
        'cls' =>'div-logo',
        'activable' => true,
        'items' => array(),
    ),
);
