<?php

return array(
    'linux' => array(
        'title' => 'Линукс',
        'href' => 'doc.php?path=linux',
        'style' =>'border: 4px dotted #000000;',
        'img' =>'logo/linux.png',
        'cls' =>'div-logo',
        'items' => array(),
    ),
    'php' => array(
        'title' => 'PHP: Hypertext Preprocessor',
        'href' => 'doc.php?path=php',
        'style' =>'border: 4px dotted #8ba9d9;',
        'img' =>'logo/php.png',
        'cls' =>'div-logo',
        'items' => array(),
    ),
    'mysql' => array(
        'title' => 'MySQL',
        'href' => 'doc.php?path=mysql',
        'style' =>'border: 4px dotted #004b62;',
        'img' =>'logo/mysql.png',
        'cls' =>'div-logo',
        'items' => array(),
    ),
    'proectirovanie' => array(
        'title' => 'Проектирование: Шаблоны и алгоритмы',
        'href' => 'architecture.php',
        'style' =>'border: 4px dotted #004b62;',
        'img' =>'logo/design.png',
        'cls' =>'div-logo',
        'items' => array(
            'patterns' => array(
                'title' => 'ООП Шаблоны проектирования',
                'href' => 'doc.php?path=patterns',
                'style' =>'border: 4px dotted #004b62;',
                'img' =>'logo/mvc.png',
                'cls' =>'div-logo',
                'items' => array(),
            ),
        ),
    ),
    'htmlcss' => array(
        'title' => 'HTML5 и CSS3',
        'href' => '#',
        'style' =>'border: 4px dotted #000000;',
        'img' =>'logo/htmlcss.png',
        'cls' =>'div-logo',
        'items' => array(),
    ),
    'javascript' => array(
        'title' => 'JavaScript',
        'href' => 'js.php',
        'style' =>'border: 4px dotted #3dade9;',
        'img' =>'logo/javascript.png',
        'cls' =>'div-logo',
        'items' => array(
            'js' => array(
                'title' => 'JavaScript',
                'href' => 'doc.php?path=js',
                'style' =>'border: 4px dotted #3dade9;',
                'img' =>'logo/javascript.png',
                'cls' =>'div-logo',
                'items' => array(),
            ),
            'jquery' => array(
                'title' => 'jQuery',
                'href' => '#',
                'style' =>'border: 4px dotted #0868ab;',
                'img' =>'logo/jqurery.png',
                'cls' =>'div-logo',
                'items' => array(),
            ),
            'extjs' => array(
                'title' => 'extjs',
                'href' => '#',
                'style' =>'border: 4px dotted #009900;',
                'img' =>'logo/extjs.png',
                'cls' =>'div-logo',
                'items' => array(),
            ),
            'angular' => array(
                'title' => 'angular',
                'href' => '#',
                'style' =>'border: 4px dotted #e23237;',
                'img' =>'logo/angular.png',
                'cls' =>'div-logo',
                'items' => array(),
            ),
            'backbone' => array(
                'title' => 'backbone',
                'href' => '#',
                'style' =>'border: 4px dotted #0072b9;',
                'img' =>'logo/backbone.png',
                'cls' =>'div-logo',
                'items' => array(),
            ),
            'knockout' => array(
                'title' => 'knockout',
                'href' => '#',
                'style' =>'border: 4px dotted #000000;',
                'img' =>'logo/knockout.png',
                'cls' =>'div-logo',
                'items' => array(),
            ),
            'ember' => array(
                'title' => 'ember',
                'href' => '#',
                'style' =>'border: 4px dotted #ff492b;',
                'img' =>'logo/ember.png',
                'cls' =>'div-logo',
                'items' => array(),
            ),
            'react' => array(
                'title' => 'react',
                'href' => '#',
                'style' =>'border: 4px dotted #00dbfb;',
                'img' =>'logo/react.png',
                'cls' =>'div-logo',
                'items' => array(),
            ),
            'dojo' => array(
                'title' => 'dojo',
                'href' => '#',
                'style' =>'border: 4px dotted #000000;',
                'img' =>'logo/dojo.png',
                'cls' =>'div-logo',
                'items' => array(),
            ),
        ),
    ),
    'zf2' => array(
        'title' => 'Zend Framework 2',
        'href' => '#',
        'style' =>'border: 4px dotted #0fb700;',
        'img' =>'logo/zf.png',
        'cls' =>'div-logo',
        'items' => array(),
    ),
    'bootstrap' => array(
        'title' => 'Twitter Bootstrap',
        'href' => '#',
        'style' =>'border: 4px dotted #00a7d4;',
        'img' =>'logo/bootstrap.png',
        'cls' =>'div-logo',
        'items' => array(),
    ),
    'doctrine' => array(
        'title' => 'Doctrine ORM',
        'href' => '#',
        'style' =>'border: 4px dotted #ff852f;',
        'img' =>'logo/doctrine.png',
        'cls' =>'div-logo',
        'items' => array(),
    ),
    'git' => array(
        'title' => 'GIT SCM',
        'href' => 'doc.php?path=git',
        'style' =>'border: 4px dotted #ff3929;',
        'img' =>'logo/git.png',
        'cls' =>'div-logo',
        'items' => array(),
    ),
    'hg' => array(
        'title' => 'Mercurial SCM',
        'href' => 'doc.php?path=hg',
        'style' =>'border: 4px dotted #999999;',
        'img' =>'logo/hg.png',
        'cls' =>'div-logo',
        'items' => array(),
    ),
    'mongo' => array(
        'title' => 'MongoDB: NOSQL СУБД',
        'href' => '#',
        'style' =>'border: 4px dotted #009900;',
        'img' =>'logo/mongo.png',
        'cls' =>'div-logo',
        'items' => array(),
    ),
    'redis' => array(
        'title' => 'Redis: REmote DIctionary Server',
        'href' => '#',
        'style' =>'border: 4px dotted #bb1207;',
        'img' =>'logo/redis.png',
        'cls' =>'div-logo',
        'items' => array(),
    ),
    'smarty' => array(
        'title' => 'Smarty: PHP Template Engine',
        'href' => '#',
        'style' =>'border: 4px dotted #ffc12b; background: #ffc12b;',
        'img' =>'logo/smarty.png',
        'cls' =>'div-logo',
        'items' => array(),
    ),
    'sphinx' => array(
        'title' => 'Sphinx: Open Source Search Engine',
        'href' => '#',
        'style' =>'border: 4px dotted #2bb3dd;',
        'img' =>'logo/sphinx.png',
        'cls' =>'div-logo',
        'items' => array(),
    ),
    'yii' => array(
        'title' => 'YII: PHP Framework',
        'href' => '#',
        'style' =>'border: 4px dotted #2bb3dd;',
        'img' =>'logo/yii.png',
        'cls' =>'div-logo',
        'items' => array(),
    ),
    'arduino' => array(
        'title' => 'Ардуино скетчи',
        'href' => 'doc.php?path=arduino',
        'style' =>'border: 4px dotted #2bb3dd;',
        'img' =>'logo/arduino.png',
        'cls' =>'div-logo',
        'items' => array(),
    ),
    'c' => array(
        'title' => 'Си++',
        'href' => 'doc.php?path=arduino',
        'style' =>'border: 4px dotted #004381;',
        'img' =>'logo/cpp.png',
        'cls' =>'div-logo',
        'items' => array(),
    ),
    'books' => array(
        'title' => 'Полезные книги',
        'href' => 'books.php',
        'style' =>'border: 4px dotted #561311;',
        'img' =>'logo/books.png',
        'cls' =>'div-logo',
        'items' => array(
            'algorithms' => array(
                'title' => 'Алгоритмы. Построение и анализ Авторы: Томас Кормен, Чарльз Лейзерсон, Рональд',
                'href' => 'doc.php?path=algorithms',
                'style' =>'border: 4px dotted #000000;',
                'img' =>'logo/books/algo.png',
                'cls' =>'div-logo',
                'items' => array(),
            ),
            'architecture' => array(
                'title' => 'Архитектура корпоративных приложений (М. Фаулер)',
                'href' => 'doc.php?path=architecture',
                'style' =>'border: 4px dotted #000000;',
                'img' =>'logo/books/architect.png',
                'cls' =>'div-logo',
                'items' => array(),
            ),
            'cleancode' => array(
                'title' => 'Чистый код Р. Мартин',
                'href' => 'doc.php?path=cleancode',
                'style' =>'border: 4px dotted #000000;',
                'img' =>'logo/books/clean.png',
                'cls' =>'div-logo',
                'items' => array(),
            ),
            'extreme' => array(
                'title' => 'Экстремальное программирование: разработка через тестирование. Кент Бек. (Test-driven Development by Example).',
                'href' => 'doc.php?path=extreme',
                'style' =>'border: 4px dotted #000000;',
                'img' =>'logo/books/exstreme.png',
                'cls' =>'div-logo',
                'items' => array(),
            ),
            'perfect' => array(
                'title' => 'Совершенный код С. Макконнелл',
                'href' => 'doc.php?path=perfect',
                'style' =>'border: 4px dotted #000000;',
                'img' =>'logo/books/ideal.png',
                'cls' =>'div-logo',
                'items' => array(),
            ),
            'artofprogramming' => array(
                'title' => 'Искусство программирования Д. Кнут',
                'href' => 'doc.php?path=artofprogramming',
                'style' =>'border: 4px dotted #000000;',
                'img' =>'logo/books/knut.png',
                'cls' =>'div-logo',
                'items' => array(),
            ),
            'nosql' => array(
                'title' => 'NoSQL Distilled Мартин Фаулер',
                'href' => 'doc.php?path=nosql',
                'style' =>'border: 4px dotted #000000;',
                'img' =>'logo/books/nosql.png',
                'cls' =>'div-logo',
                'items' => array(),
            ),
            'designpatterns' => array(
                'title' => 'Паттерны проектирования Э. Гамма, Р. Хелм, Р. Джонсон, Д. Влиссидес',
                'href' => 'doc.php?path=designpatterns',
                'style' =>'border: 4px dotted #000000;',
                'img' =>'logo/books/oop.png',
                'cls' =>'div-logo',
                'items' => array(),
            ),
            'pragmatic' => array(
                'title' => 'Программист-прагматик Э. Хант, Д. Томас',
                'href' => 'doc.php?path=pragmatic',
                'style' =>'border: 4px dotted #000000;',
                'img' =>'logo/books/pragmatik.png',
                'cls' =>'div-logo',
                'items' => array(),
            ),
            'refactoring' => array(
                'title' => 'Рефакторинг. Улучшение существующего кода (Мартин Фаулер)',
                'href' => 'doc.php?path=refactoring',
                'style' =>'border: 4px dotted #000000;',
                'img' =>'logo/books/refact.png',
                'cls' =>'div-logo',
                'items' => array(),
            ),
            'structure' => array(
                'title' => 'Структура и Интерпретация Компьютерных Программ Авторы: Харольд Абельсон, Джеральд Джей Сассман',
                'href' => 'doc.php?path=structure',
                'style' =>'border: 4px dotted #000000;',
                'img' =>'logo/books/structure.png',
                'cls' =>'div-logo',
                'items' => array(),
            ),
            'ddd' => array(
                'title' => 'Предметно-ориентированное проектирование (DDD). Структуризация сложных программных систем. Ерик Эванс. (Tackling Complexity in the Heart of Software)',
                'href' => 'doc.php?path=ddd',
                'style' =>'border: 4px dotted #000000;',
                'img' =>'logo/books/ddd.png',
                'cls' =>'div-logo',
                'items' => array(),
            ),
        ),
    ),
);
